name: Test clone a repo
on:
  workflow_dispatch:

jobs:
  test-clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the other repo
        uses: actions/checkout@v4
        with:
          repository: smithlabcode/methbase_private
          path: methbase_private
      - name: See what's in logs
        run: |
          ls -lhR
